version: '3.7'

services:

  web:
    build: .
    ports:
      - 80:80 
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "waitress_serve.py"]
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres


volumes:
  postgres_data:
  